# Loops

Topics:
    1. **while** loops
    2. **for** loops
    
### While loops
The syntax for a **while** is
    
    **while *condition* 
        *loop body* 
      end
    **
        
For example, we could use **while** to count or to iterate over an array.


In [2]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
myfriends = ["Haha", "Hasdf", "adsfoj", "asjdf", "fasjdfo"]

i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you.")
    i += 1
end

Hi Haha, it's great to see you.
Hi Hasdf, it's great to see you.
Hi adsfoj, it's great to see you.
Hi asjdf, it's great to see you.
Hi fasjdfo, it's great to see you.


### For loops

The syntax fir a **for** loop is
    **for *var* in *loop iterable* **
        ** *loop body* **
    **end**

We could use a for loop to generate the same results as either of the examples above:

In [5]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [6]:
myfriends = ["Haha", "Hasdf", "adsfoj", "asjdf", "fasjdfo"]

for friend in myfriends
    println("Hi $friend, it's great to see you.")
end

Hi Haha, it's great to see you.
Hi Hasdf, it's great to see you.
Hi adsfoj, it's great to see you.
Hi asjdf, it's great to see you.
Hi fasjdfo, it's great to see you.


Note that we could replace **in** with either **=** or **∈**

In [7]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [8]:
for n ∈ 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


Now let's use **for** loops to create some addition tables, where the value of every entry is the sum of its row and column indices.

First, we initialize an array with zeros.

In [9]:
m, n = 5, 5
a = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [10]:
for i in 1:m
    for j in 1:n
        a[i, j] = i + j
    end
end
a

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Here's some syntatic sugar for the same nested **for** loop

In [11]:
b = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [12]:
for i in 1:m, j in 1:n
    b[i, j] = i + j
end
b

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The more "Julia" way to create this addition table would have been with an __array comprehension__.

In [14]:
c = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In the next example, we embed an array cinorehension in a **for** loop, generating addition tables of growing size.

In [15]:
for n in 1:10
    A = [i + j for i in 1:m, j in 1:n]
    display(A)
end

5×1 Array{Int64,2}:
 2
 3
 4
 5
 6

5×2 Array{Int64,2}:
 2  3
 3  4
 4  5
 5  6
 6  7

5×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6
 5  6  7
 6  7  8

5×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8
 6  7  8  9

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

5×6 Array{Int64,2}:
 2  3  4  5   6   7
 3  4  5  6   7   8
 4  5  6  7   8   9
 5  6  7  8   9  10
 6  7  8  9  10  11

5×7 Array{Int64,2}:
 2  3  4  5   6   7   8
 3  4  5  6   7   8   9
 4  5  6  7   8   9  10
 5  6  7  8   9  10  11
 6  7  8  9  10  11  12

5×8 Array{Int64,2}:
 2  3  4  5   6   7   8   9
 3  4  5  6   7   8   9  10
 4  5  6  7   8   9  10  11
 5  6  7  8   9  10  11  12
 6  7  8  9  10  11  12  13

5×9 Array{Int64,2}:
 2  3  4  5   6   7   8   9  10
 3  4  5  6   7   8   9  10  11
 4  5  6  7   8   9  10  11  12
 5  6  7  8   9  10  11  12  13
 6  7  8  9  10  11  12  13  14

5×10 Array{Int64,2}:
 2  3  4  5   6   7   8   9  10  11
 3  4  5  6   7   8   9  10  11  12
 4  5  6  7   8   9  10  11  12  13
 5  6  7  8   9  10  11  12  13  14
 6  7  8  9  10  11  12  13  14  15